# Generated by Django 4.0.3 on 2022-03-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('sem_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subject_subject', to='sem.semester')),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
    ]
