# Generated by Django 4.0.3 on 2022-03-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subject', '0001_initial'),
        ('systemuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filefield', models.FileField(upload_to='Document/')),
                ('filename', models.CharField(max_length=30)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubjectDocument_Subject', to='subject.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubjectDocument_user', to='systemuser.systermuser')),
            ],
            options={
                'verbose_name_plural': 'SubjectDocument',
            },
        ),
    ]
